# This workflow runs Lighthouse CI to audit accessibility (and other categories) on build.
name: Lighthouse CI

# Controls when the action will run. It triggers on pushes or pull requests to the main branch,
# but only if files in WebApp/ or workflow files change.
on:
  push:
    paths:
      - 'WebApp/**'
      - '.github/workflows/*.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'WebApp/**'
      - '.github/workflows/*.yml'
    branches: [ main ]

# Single job named "lhci" to run Lighthouse audits
jobs:
  lhci:
    # Runs on the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Instruct all commands to run from the WebApp directory
    defaults:
      run:
        working-directory: WebApp

    steps:
      # Check out the repository to access source code and configs
      - uses: actions/checkout@v3

      # Set up Node.js (version 18+) for Lighthouse
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install dependencies in WebApp
      - run: npm ci

      # Run Lighthouse CI in "autorun", which will:
      # Build the production bundle (npm run build)
      # Serve the build (npm run serve)
      # Run audits on the URLs specified in WebApp/.lighthouserc.js
      # Assert that the accessibility category score is above 90%, otherwise fail.
      - run: npx lhci autorun
