# This workflow runs ESLint with accessibility rules on any changes under WebApp/ or to workflow files.
name: ESLint + a11y

# Controls when the action will run. It triggers on pushes or pull requests to the main branch,
# but only if files in WebApp/ or workflow files change.
on:
  push:
    paths:
      - 'WebApp/**'
      - '.github/workflows/*.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'WebApp/**'
      - '.github/workflows/*.yml'
    branches: [ main ]

# Single job named "eslint" to lint the code
jobs:
  eslint:
    # Runs on the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Instruct all commands to run from the WebApp directory
    defaults:
      run:
        working-directory: WebApp

    steps:
      # Check out the repository to access source code and configs
      - uses: actions/checkout@v3

      # Set up Node.js (version 18+) for linting
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      # Install dependencies in WebApp
      - run: npm ci

      # Once npm run lint warnings have been fixed (currently there are 10), 
      # switch the run step on line 47 to:
      # - run: npm run lint -- --max-warnings=0
      # The line above will essentially treat all future warnings as failures and stop merges with main.
      # I believe it will also stop warnings from being output in the check on GitHub (maybe not, idk), BUT
      # you should still be able to see future warnings by using npm run lint with the CLI.
      - run: npm run lint
